spring:
  application:
    name: Backend for modded Tic Tac Toe
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_ID}
            client-secret: ${GITHUB_SECRET}
            redirect-uri: ${REDIRECT_URL}/login/oauth2/code/github
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        domain: ${COOKIE_DOMAIN}
        http-only: false
        same-site: none
        secure: true

auth:
  target-url: ${TARGET_URL}
